spec/file-spec.coffee, src/file.coffee
People are getting `ENOENT open` errors when they change branches and a watched file does not exist on the switched-to branch: https://github.com/atom/atom/issues/4850
Pathwatcher is emitting a `change` event sometime after the file is deleted, and it cannot read the file again. [this line](https://github.com/atom/node-pathwatcher/blob/8417d3d4b96bd8520c569cf9df3ca0bde83547b0/src/file.coffee#L311) is failing.
[This line](https://github.com/atom/node-pathwatcher/blob/8417d3d4b96bd8520c569cf9df3ca0bde83547b0/src/file.coffee#L318) is suspicious as well because it fires a change event on it's own after a delay. 
This PR separates the real change event originating in the native code from the resurrection change event. When this comes up again, the event type will be in the error message, and …
=> Add specific resurrect event handling for resurrection

spec/directory-spec.coffee, spec/file-spec.coffee, src/file.coffee
Having more async IO will be the initial effort to support remote filesystem
Here, the code introduces some optimizations to reduce the number of filesystem calls and assumes:
* Synchronous functions are being deprecated
* Q promises are the standard way of code in Atom (I think promises are good in the case a future decision was taken to introduce the await / async syntactic sugar of JS ES6/7)
Some other PRs are following with the same approach
=> Change File methods to do more with async node API wrapped with Q promises

spec/directory-spec.coffee, src/directory.coffee
`Directory.existsSync()` is also introduced in v4, but it's hard to
upgrade Atom core to `pathwatcher@4.0.0` because it changes `File.exists()`
to be async instead of sync. This will be a useful upgrade to Atom core
so the TODO in `git-repository-provider.coffee` in `directoryExistsSync()`
can be fixed: https://github.com/atom/atom/commit/e04f17fe5f9677b9f6f50520449baee5a24eaeff.
=> Add Directory.existsSync() (in preparation for bump to v3.2.1).

package.json
Meteor.js depends on node-pathwatcher and there was a bug in one of emissary dependants, so it would be nice, if you merge it, and I could update meteor.
Bug: https://github.com/mquandalle/meteor-harmony/issues/37#issuecomment-73725823
=> Bump emissary

spec/pathwatcher-spec.coffee, src/common.cc, src/common.h, src/pathwatcher_linux.cc, src/pathwatcher_mac.mm, src/pathwatcher_win.cc
The error will have a numeric 'code', which is the system errno
value (NOT the uv errno value).
(I spent quite a while trying to convert this into a string like `'ENOENT'` but uv actually makes that hard by not exposing their internal errno conversion API (https://github.com/libuv/libuv/issues/79); and posix only gives you `strerror` which gets you the English description rather than the short string.)
This change also stops it from being a TypeError, which seems reasonable... makes sense to use NaNThrowTypeError for "String required" but not for "syscall failed".
This change also ensures that if the initial inotify/kqueue init syscall failed, we make Watch calls fail immediately instead of trying to call the follow-up call.
=> Expose kevent/inotify errnos on thrown error

spec/file-spec.coffee, src/file.coffee
Use old implementation of `File::write()` back when it was synchronous:
https://github.com/atom/node-pathwatcher/commit/88fe3219b736bcb6510f73ecb7fd053187132d87
=> Implement File::writeSync().

src/directory.coffee
The current docs (v0.204.0) are missing argument and return value docs for [`Directory.contains`](https://atom.io/docs/api/v0.204.0/Directory#instance-contains). Fill them in.
=> Fill arg and return docs for `Directory.contains`

spec/directory-spec.coffee, spec/file-spec.coffee, src/directory.coffee, src/file.coffee
`@symlink` is assigned in the constructors of `File` and `Directory`,
but the property is currently undocumented. Add an instance property and
appropriate documentation.
=> Add getters for File/Directory symlink property

package.json, script/cibuild, src/directory.coffee, src/file.coffee
Now that native promises work in Electron, there's no reason to continue using the Q library. Its API is nonstandard and it seems to swallow errors in unpredictable ways.
Since the API of Q's promises differs slightly from native promises, this requires a major version increment.
/cc @kevinsawicki since you've done a lot with pathwatcher.
=> Use native promises instead of Q library

src/directory.coffee
`Returns` must be separated by a blank line in order to be parsed
correctly for the generated documentation.
v1.0.11 [`Directory::create`](https://atom.io/docs/api/v1.0.11/Directory#instance-create) rendering does not split the return value nor mark `mode` as optional:
=> Add linebreak for Directory::create return val

binding.gyp
I tried to build with VS 2015 and failed because of this warning.
Maybe there are better fix but at least with this patch I was able to build.
=> Windows and VS2015: add 4577 to the disabled warnings

package.json, spec/file-spec.coffee, src/file.coffee
Refs https://github.com/atom/text-buffer/pull/97
=> Bust file's digest cache when writing to the file

.travis.yml, script/cibuild
Just investigating if pathwatcher actually builds on Node 4.
Refs atom/text-buffer#99.
=> Switch travis.yml to use nodejs

src/common.h, src/pathwatcher_win.cc
Handle are deprecated in favor of Local.
This should fix https://github.com/atom/node-pathwatcher/issues/96
A clean `npm install`, on my pc, always fail but the subsequent run works fine.
And without the patch cannot build on Windows, with I can: so I hope this is enough.
=> Use Local instead of Handle

spec/file-spec.coffee, src/file.coffee
The `File::read` method is already using a stream to process the file's content with iconv on the fly, but there's no way for the consumer of a `File` to get a read stream for the proper encoding - one can always use the `fs` APIs to get a stream but it has to include `iconv-lite` as dependency if it want to behave the same as the `File` API.
This PR adds a public `createReadStream` method on the `File` object that encapsulates the stream creation that was previously in the `read` method.
=> Feature file stream

spec/file-spec.coffee, src/main.coffee
Fixes #104 and subsequently atom/tabs#160, atom/find-and-replace#634, atom/fuzzy-finder#168.
The issue was that `Move To Trash`, which is how `tree-view` deletes items, was not being interpreted as a `delete` event by `HandleWatcher`. 
This PR adds a check in `HandleWatcher` any time a `rename` event is emitted to see if it was a move to a `.Trash` dir. If it was, it emits a `delete` event in stead of a `rename` event to the `PathWatcher`.
A spec is included, but testing can also be done in any of the referenced packages by recreating the steps in the respective issues.
Some questions/room for improvement:
1. Is `HandleWatcher` low enough to be handling this or should it be done in `pathwatcher_unix.cc`?
2. Should the [regular expression](https://github.com/atom/node-pathwatcher/compare/at …
=> Emit delete event when file moved to trash on OS X

spec/file-spec.coffee, src/file.coffee
Refs.: atom/atom#11794
This pull-request introduces two new methods to the `File` object, which make sure that deleting and writing to a file is flushed to disk. Moreover, they'll ask to elevate privileges in case permissions are insufficient: in particular, on Mac, it uses the `sync` command line utility to flush pending disk writes, which should (almost) be a drop-in replacement for `fdatasync` sys calls.
Writing tests for these two methods is somewhat tricky, especially for the `sync` behavior. I ended up just verifying the basic functionality of both methods, and testing this out manually on Atom following the reproduction steps provided on the aforementioned issue.
=> Add File.prototype.safe{Write,Remove}Sync

spec/pathwatcher-spec.coffee, src/file.coffee
This fixes an error I introduced in #107 caused by a typo when re-throwing an error in `safeRemoveSync`.
=> Fix typos when `runas` fails during `safeRemoveSync`

package.json, src/pathwatcher_win.cc
This pull request fixes an Access Violation exception that was occurring on Windows when closing a file handle while a `WaitForMultipleObjects` call was still in progress. As specified on MSDN, «if one of the handles is closed while the wait is still pending, the function's behavior is undefined». This was causing hard crashes on packages like the tree-view where a lot of I/O is performed in the tests.
This pull request fixes it by always closing the file handle after `WaitForMultipleObjects` returns. Now, when the user calls `.unwatch()`, we will mark the handle as "canceled", wake up `PlatformThread`, wait until it finishes waiting on all the handles (i.e. when `WaitForMultipleObjects` returns) and then delete the desired file handle in the main thread.
=> Fix race condition on Windows

.travis.yml, package.json, src/main.coffee
This pull request changes path watcher so that it can be required while generating the snapshot. To do so we have:
1. Changed `HandleWatcher` and `PathWatcher` to stop using Node's `EventEmitter` and replace it with `event-kit`.
2. Moved the `binding.setCallback` call inside the `watch` function, so that we execute it just once the first time `watch` is called.
=> Enable v8 snapshot for this module

package.json, spec/file-spec.coffee, src/file.coffee
We may have been re-reading the file on every change event in order to suppress redundant change events which didn't actually affect the file's content. But for large files, loading the file's content into a string actually throws an exception. And in general, the read/transcode operation is very expensive. I think we can deal w/ redundant change events at a higher level in `text-buffer`.
Refs https://github.com/atom/atom/issues/7210
=> Don't re-read the file on every change event

package.json, spec/file-spec.coffee, src/file.coffee
This behavior is now implemented in TextBuffer, and uses the async `spawn-as-admin` module instead of `runas`, which is synchronous.
Refs https://github.com/atom/text-buffer/pull/246
=> Remove privilege escalation functionality

src/pathwatcher_win.cc
Fixes https://github.com/atom/atom/issues/15223
Apparently, when listening for changes to folders on SMB drives, the [`GetOverlappedResult`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683209(v=vs.85).aspx) API can succeed (return true) but set the `numberOfBytesTransferred` parameter to zero. Previously, our code was expecting that if `GetOverlappedResult` returned true, then there would always be at least one `FILE_NOTIFY_INFORMATION` structure to read.
=> Avoid reading garbage when GetOverlappedResult succeeds w/ zero bytes

src/file.coffee
Documentation for the return value of `File.read()` is incomplete: promise can resolve to `null` if the file in question does not exist.
Note lines 268-270:
https://github.com/atom/node-pathwatcher/blob/ea686aeffc33d99445a6480d3eafd477b8738ef8/src/file.coffee#L268-L270
For context:
https://github.com/atom/node-pathwatcher/blob/ea686aeffc33d99445a6480d3eafd477b8738ef8/src/file.coffee#L254-L272
=> Fix File.read() documentation

src/common.cc, src/handle_map.cc, src/handle_map.h, src/main.cc, src/unsafe_persistent.h
see https://electronjs.org/blog/nodejs-native-addons-and-electron-5
> Electron 5.0 includes a version of V8 that has finally removed v8::Handle for good, and native Node.js addons that still use it will need to be updated before they can be used with Electron 5.0.
=> replace Handle with Local

Gruntfile.coffee, src/common.cc, src/common.h, src/handle_map.cc, src/handle_map.h, src/main.cc, src/pathwatcher_win.cc, src/unsafe_persistent.h
Depends on the work @abnerlee started in https://github.com/atom/node-pathwatcher/pull/127.
Meteor can use a fork of the `pathwatcher` package for now, but it would be great to see these changes released officially sometime soon!
Related: https://github.com/atom/watcher/pull/224#issuecomment-488084530
=> Fix all compilation errors and warnings for Node.js 12 (V8 7.4).

.travis.yml, appveyor.yml, package.json, spec/file-spec.coffee
This PR adds checks on both travis and AppVeyor for Node v12 now that this package supports it
=> CI: Test package on Node v12

spec/file-spec.coffee, src/file.coffee
Revies and closes #112
Fixes #110 
This emits 'did-change' when writeSync is used.
The tests are included. The CI passes.
=> writeSync emits did-change event [Revive]

binding.gyp
Building on win32 is failing for electron version 11.4.7. We need to add
the errors on the warning list to have a passing build on https://github.com/atom/atom/pull/22687
An altenative would be to fix the warnings. Right now there is no
capacity for us to do the fixes
=> Add 2220 and 4309 to warning list
